# Generated by Django 5.2.12 on 2026-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_workbook_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_file', models.CharField(db_index=True, max_length=64)),
                ('source_path', models.TextField(blank=True)),
                ('course_code', models.CharField(blank=True, db_index=True, max_length=3)),
                ('module_path', models.TextField(blank=True)),
                ('workbook_title', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=128)),
                ('row_number', models.PositiveIntegerField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(blank=True, max_length=64)),
                ('difficulty', models.CharField(blank=True, max_length=64)),
                ('question_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('raw_payload', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course_code', 'source_file', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('source_file', 'sheet_name', 'row_number'), name='unique_question_bank_entry_row')],
            },
        ),
    ]
