# Generated by Django 5.2.12 on 2026-04-02 09:00

import re

from django.db import migrations, models


ALLOWED_QUESTION_TYPES = (
    "Theory",
    "MCQ",
    "Coding",
    "SQL",
    "Practical",
    "Scenario-Based",
    "Short Answer",
)

QUESTION_TYPE_CHOICES = [(value, value) for value in ALLOWED_QUESTION_TYPES]

QUESTION_TYPE_ALIASES = {
    "application": "Practical",
    "coding": "Coding",
    "command": "Practical",
    "concept": "Theory",
    "conceptual": "Theory",
    "design": "Practical",
    "mcq": "MCQ",
    "one word": "Short Answer",
    "one word/command": "Short Answer",
    "one-word": "Short Answer",
    "practical": "Practical",
    "project": "Practical",
    "scenario": "Scenario-Based",
    "scenario based": "Scenario-Based",
    "scenario-based": "Scenario-Based",
    "short answer": "Short Answer",
    "short-answer": "Short Answer",
    "size": "Short Answer",
    "sql": "SQL",
    "technical": "Theory",
    "theory": "Theory",
    "two words": "Short Answer",
    "word": "Short Answer",
    "write yaml": "Coding",
}

QUESTION_VERBS = (
    "what",
    "which",
    "how",
    "why",
    "when",
    "where",
    "who",
    "create",
    "write",
    "build",
    "implement",
    "use",
    "calculate",
    "find",
    "sort",
    "fill",
    "clean",
    "compare",
    "demonstrate",
    "assign",
    "take",
    "convert",
    "swap",
    "display",
    "show",
    "determine",
    "identify",
    "analyze",
    "plot",
    "graph",
    "retrieve",
    "explain",
)


def normalize_text(value):
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def normalize_key(value):
    return normalize_text(value).lower()


def normalize_question_type(value):
    return QUESTION_TYPE_ALIASES.get(normalize_key(value), "")


def looks_like_question(text):
    cleaned = normalize_text(text)
    if not cleaned:
        return False
    lowered = cleaned.lower()
    if "?" in cleaned:
        return True
    if lowered.startswith(QUESTION_VERBS):
        return True
    return any(f" {verb} " in f" {lowered} " for verb in QUESTION_VERBS)


def infer_question_type(entry):
    has_options = any(
        normalize_text(getattr(entry, field_name))
        for field_name in ("option_a", "option_b", "option_c", "option_d")
    )
    combined = normalize_key(
        f"{entry.question_text} {entry.context} {entry.details} {entry.correct_answer}"
    )

    if has_options:
        return "MCQ"
    if any(token in combined for token in ("one word", "two words", "one-word", "fill in the blank")):
        return "Short Answer"
    if any(token in combined for token in ("sql", "query", "select ", " join ", "mysql", "database", "group by")):
        return "SQL"
    if any(token in combined for token in ("python", "code", "program", "function", "class", "script", "keras", "tensorflow", "pandas", "numpy")):
        return "Coding"
    if "scenario" in combined:
        return "Scenario-Based"
    if any(token in combined for token in ("practical", "command", "operation", "project", "excel", "tableau", "power bi", "dashboard", "git ")):
        return "Practical"
    if looks_like_question(entry.question_text):
        return "Theory"
    return "Practical"


def normalize_existing_question_types(apps, schema_editor):
    QuestionBankEntry = apps.get_model("questions", "QuestionBankEntry")
    batch = []

    for entry in QuestionBankEntry.objects.all().iterator():
        current_type = normalize_text(entry.question_type)
        normalized_type = normalize_question_type(current_type) or infer_question_type(entry)
        if current_type == normalized_type:
            continue
        entry.question_type = normalized_type
        batch.append(entry)
        if len(batch) >= 500:
            QuestionBankEntry.objects.bulk_update(batch, ["question_type"], batch_size=500)
            batch.clear()

    if batch:
        QuestionBankEntry.objects.bulk_update(batch, ["question_type"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_question_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="questionbankentry",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=QUESTION_TYPE_CHOICES,
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbankentry",
            constraint=models.CheckConstraint(
                check=models.Q(question_type="") | models.Q(question_type__in=ALLOWED_QUESTION_TYPES),
                name="question_bank_entry_valid_type",
            ),
        ),
    ]
