# Generated by Django 5.2.12 on 2026-04-02 12:10

import json

from django.db import migrations


ANSWER_KEYS = {"answer", "correct answer", "expected answer", "expected_answer"}


def sanitize_payload(raw_payload):
    if not raw_payload:
        return ""
    try:
        data = json.loads(raw_payload)
    except (TypeError, ValueError):
        return raw_payload
    if not isinstance(data, dict):
        return raw_payload

    changed = False
    for key in list(data):
        if str(key).strip().lower() in ANSWER_KEYS and data[key] != "":
            data[key] = ""
            changed = True
    if not changed:
        return raw_payload
    return json.dumps(data, ensure_ascii=False)


def clear_question_bank_answers(apps, schema_editor):
    QuestionBankEntry = apps.get_model("questions", "QuestionBankEntry")
    batch = []

    for entry in QuestionBankEntry.objects.all().iterator():
        next_correct_answer = ""
        next_raw_payload = sanitize_payload(entry.raw_payload)
        if entry.correct_answer == next_correct_answer and entry.raw_payload == next_raw_payload:
            continue

        entry.correct_answer = next_correct_answer
        entry.raw_payload = next_raw_payload
        batch.append(entry)

        if len(batch) >= 500:
            QuestionBankEntry.objects.bulk_update(batch, ["correct_answer", "raw_payload"], batch_size=500)
            batch.clear()

    if batch:
        QuestionBankEntry.objects.bulk_update(batch, ["correct_answer", "raw_payload"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_normalize_question_types"),
    ]

    operations = [
        migrations.RunPython(clear_question_bank_answers, migrations.RunPython.noop),
    ]
