# Generated by Django 5.2.12 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.CharField(choices=[('AIE', 'Artificial Intelligence Engineer'), ('CDS', 'Certified Data Scientist'), ('CDA', 'Certified Data Analyst'), ('CDE', 'Certified Data Engineer')], default='AIE', max_length=3),
        ),
    ]
